module.exports = {
    dataTypes: {
        TagEntities: "TagEntities",
        SimpleContent: "SimpleContent",
        Item: "Item",
        BingItem: "BingItem",
        SingleEntity: "SingleEntity",
        Tags: "Tags",
        Appointment: "Appointment",
        Address: "Address",
        Addresses: "Addresses",
        Task: "Task",
        Tasks: "Tasks",
        Person: "Person",
        Favorites: "Favorites",
        People: "People",
        Video: "Video",
        Files: "Files",
        Images: "Images",
        Service: "Service",
        Weather: "Weather",
        GraphSearch: "GraphSearch",
        Thought: "Thought",
        Thoughts: "Thoughts",
        CurrentAgenda: "CurrentAgenda",
        OracleStackItem: "OracleStackItem",
        Workspaces: "Workspaces",
    }
};